
server:
  port: 8091
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error: 
   include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
   include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부
  

spring:
  freemarker:
    checkTemplateLocation: false

  

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/security?serverTimezone=Asia/Seoul
    username: 'root'
    password: 'root'

 # profiles: dev  -jar class_name.jar
          

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    
    
  #security:
   #oauth2:
    #client:
     #registration:
     # google:
      # client-id: 345072234027-njpbrsdptpf5m2de8arse8i404m6mt25.apps.googleusercontent.com
      # client-secret: LyieJiQmBZEmUA7jcMu_12pJ
       #scope:
       #- email
      # - profile
       
  mvc:
    view:
      prefix: /WEB-INF/servlet/views/
      suffix: .jsp
      static-path-pattern: /resources/**
 